#include "ns3/ag-flow-recovery-phase.h"
#include "ns3/rdma-flow-multicast.h"
#include "ns3/rdma-flow-wait.h"
#include "ns3/rdma-network.h"
#include "ns3/rdma-hw.h"
#include "ns3/qbb-net-device.h"
#include "ns3/data-rate-ops.h"

namespace ns3 {

NS_OBJECT_ENSURE_REGISTERED(AgFlowRecoveryPhase);
NS_LOG_COMPONENT_DEFINE("AgFlowRecoveryPhase");

TypeId AgFlowRecoveryPhase::GetTypeId()
{
  static TypeId tid = []() {
    static TypeId tid = TypeId("ns3::AgFlowRecoveryPhase");

    tid.SetParent<RdmaFlow>();
    tid.AddConstructor<AgFlowRecoveryPhase>();
    
    AddStringAttribute(tid,
      "BitmapsAvroIn",
      "File path from where to load the Avro bitmaps of all nodes generated by the multicast phase.",
      &AgFlowRecoveryPhase::m_bitmaps_avro_in);

    AddStringAttribute(tid,
      "StatsJsonIn",
      "File path from where to load the statistics generated by the multicast phase.",
      &AgFlowRecoveryPhase::m_stats_json_in);

    return tid;
  }();
  
  return tid;
}

void AgFlowRecoveryPhase::OnFlowStarted(RdmaNetwork& network)
{
  // Build a map to convert from node ID to rank in the Allgather.
  const auto servers = network.FindMcastGroup(0).to_vector();
  for(Ptr<Node> server : servers) {
    m_id_to_rank[server->GetId()] = m_id_to_rank.size();
  }
  const int num_ranks = servers.size();


  const RdmaConfig& rdma_config{RdmaNetwork::GetInstance().GetConfig()};
  {
    struct Stats
    {
      int num_mcast_roots;
      int num_pkts_per_chunk;
      int num_chunks_per_rank;
      int num_ranks;
    };

    const Stats& stats = rdma_config.LoadFromfile<Stats>(m_stats_json_in);
    m_num_pkts_per_chunk = stats.num_pkts_per_chunk;
    m_num_chunks_per_rank = stats.num_chunks_per_rank;
    NS_ABORT_IF(stats.num_ranks != servers.size());
  }

  const int bitmap_length = m_num_pkts_per_chunk * m_num_chunks_per_rank * num_ranks;

  // The bitmap of each rank.
  std::vector<std::vector<bool>> bitmaps(servers.size(), std::vector<bool>(bitmap_length));
  for(AgRecvChunkRecord record : DeserializeAvro<AgRecvChunkRecord>(rdma_config.FindFile(m_bitmaps_avro_in))) {
    bitmaps[record.dst_rank][record.packet] = true;
  }

  // Build the map of missed packets for each rank.
  // `missed_pkts[i]` stores all missed packets of rank `i`.
  m_missed_pkts.resize(servers.size());
  for(int i = 0; i < num_ranks; i++) {
    for(int j = 0; j < bitmap_length; j++) {
      if(!bitmaps[i][j]) {
        missed_pkts[i].insert(j);
      }
    }
  }
  

  // Initially, each node will send to its right neighbor (i+1) all packets that are missed by the later,
  // and the current node has locally.
  // The immediate data is the packet index in the allgather buffer.
  for(int i = 0; i < num_ranks; i++) {
    ScheduleRank(i);
  }
}

void AgFlowRecoveryPhase::ScheduleRank(int rank)
{
    const Ptr<Node> snode = network.FindServer(m_snode);
    const Ptr<Node> dnode = network.FindServer(m_dnode);
    const Ipv4Address src_ip = GetServerAddress(snode);
    const Ipv4Address dst_ip = GetServerAddress(dnode);
    const uint16_t src_port = GetNextUniquePort(snode);
    const uint16_t dst_port = GetNextUniquePort(dnode);
    const Ptr<RdmaHw> src_rdma{snode->GetObject<RdmaHw>()};
    const Ptr<RdmaHw> dst_rdma{dnode->GetObject<RdmaHw>()};
    

    // Create the RDMA Write request.
    RdmaTxQueuePair::SendRequest sr;
    sr.payload_size = m_bytes_to_write;
    sr.multicast = false;
    sr.dip = dst_ip;          // Only useful for UD QP.
    sr.dport = dst_port;      // Only useful for UD QP.
    sr.on_send = [this]() {
      NotifyComplete();
    };

    // Create the queues on the source.
    {
        Ptr<RdmaTxQueuePair> src_tx_queue;
        Ptr<RdmaRxQueuePair> src_rx_queue;

        if(m_reliable) {
            src_tx_queue = CreateObject<RdmaReliableSQ>(snode, m_priority, src_ip, src_port, dst_ip, dst_port);
            src_rx_queue = CreateObject<RdmaReliableRQ>(DynamicCast<RdmaReliableSQ>(src_tx_queue));
        }
        else {
            src_tx_queue = CreateObject<RdmaUnreliableSQ>(snode, m_priority, src_ip, src_port);
            src_rx_queue = CreateObject<RdmaUnreliableRQ>(DynamicCast<RdmaUnreliableSQ>(src_tx_queue));
        }
        
        src_rdma->RegisterQP(src_tx_queue, src_rx_queue);

        // Post the send request on the source.
        src_tx_queue->PostSend(sr);
    }

    // Create the queues on the destination.
    {
        Ptr<RdmaTxQueuePair> dst_tx_queue;
        Ptr<RdmaRxQueuePair> dst_rx_queue;
        
        if(m_reliable) {
            dst_tx_queue = CreateObject<RdmaReliableSQ>(dnode, m_priority, dst_ip, dst_port, src_ip, src_port);
            dst_rx_queue = CreateObject<RdmaReliableRQ>(DynamicCast<RdmaReliableSQ>(dst_tx_queue));
        }
        else {
            dst_tx_queue = CreateObject<RdmaUnreliableSQ>(dnode, m_priority, dst_ip, dst_port);
            dst_rx_queue = CreateObject<RdmaUnreliableRQ>(DynamicCast<RdmaUnreliableSQ>(dst_tx_queue));
        }

        dst_rdma->RegisterQP(dst_tx_queue, dst_rx_queue);
    }
}

} // namespace ns3