#pragma once

#include "ns3/rdma-flow.h"
#include "ns3/ag-recv-chunk-record.h"
#include "ns3/rdma-serdes.h"

namespace ns3 {

/**
 * Runs the recovery phase.
 * 
 * Assumes a fat-tree where all servers IDs are in the same order.
 * 
 * Takes as input the JSON and Avro file generated by the multicast phase.
 * 
 * Uses the PFC priority 3.
 * Uses the multicast group 0.
 */
class AgFlowRecoveryPhase : public RdmaFlow
{
public:
    static TypeId GetTypeId();

protected:
    void OnFlowStarted(RdmaNetwork& network) override;

private:
    void ScheduleRank(RdmaNetwork& network, int rank);  // <-- pass network reference

private:
    //! From where to load the bitmaps of the received chunks.
    std::string m_bitmaps_avro_in;
    //! From where to load the configuration and some statistics.
    std::string m_stats_json_in;
    //! Count of MTU-sized packets per chunk.
    uint32_t m_num_pkts_per_chunk{};
    //! Count of local chunks per node.
    uint32_t m_num_chunks_per_rank{};
    //! PFC priority to use for all communications. Fixed.
    priority_t m_priority{3};
    //! Just maps Node ID to rank in the allgather.
    std::unordered_map<int, int> m_id_to_rank;
    //! Each rank's missed packets.
    std::vector<std::unordered_set<int>> m_missed_pkts;

    //! Source and destination node IDs for the flow.
    int m_snode{};
    int m_dnode{};

    //! Bytes to write in this recovery phase.
    uint32_t m_bytes_to_write{0};

    //! Whether to use reliable transmission.
    bool m_reliable{true};
};

} // namespace ns3

